<?php

/**
 * @file
 *
 */

// Namespace for adding relationships 
define('MYNS_URI', 'http://islandora.ca/BDH/RELS/temp/');

/**
 * Implements hook_menu().
 */
function islandora_relationship_editor_menu() {
  $items['islandora/object/%/manage/relationships'] = array(
    'title' => 'Relationships',
    'description' => 'Add, remove, or validate related objects',
    'file' => 'Main.inc',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_relationship_editor_display_relationships', 2),
    'access arguments' => array(ISLANDORA_METADATA_EDIT),
    'type' => MENU_LOCAL_TASK,
  );
  $items['islandora/object/%/manage/relationships/add'] = array(
    'title' => t('Add relationships'),
    'description' => t('Add a new related object'),
    'file' => 'Add.inc',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_relationship_editor_add_relationships', 2),
    'access arguments' => array(ISLANDORA_METADATA_EDIT),
    'type' => MENU_LOCAL_ACTION,
  );
  $items['islandora/object/%/manage/relationships/delete/%/%/%'] = array(
    'title' => t('Delete relationship'),
    'description' => t('Delete a relationship'),
    'file' => 'Delete.inc',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_relationship_editor_delete_relationships', 2, 6, 7, 8),
    'access arguments' => array(ISLANDORA_METADATA_EDIT),
    'type' => MENU_CALLBACK,
  );

  return $items;
}


/**
 * Implements hook_theme().
 */
function islandora_relationship_editor_theme() {
  return array(
    'relationship_editor_table' => array(
      'variables' => array('relationships' => NULL),
      'template' => 'relationship-editor-table',
      'path' => drupal_get_path('module', 'islandora_relationship_editor') . '/theme',
    ),
    'islandora_relationship_editor_related_objects' => array(
      'variables' => array('islandora_object' => NULL),
      'template' => 'theme/related-objects',
      'file' => 'theme/related_objects.theme.inc',
    ),
  );
}

/**
 * Gets delete menu path for a relationship.
 */
function islandora_relationship_editor_get_delete_path($object_pid, $namespace, $relationship, $target_pid) {
  $namespace = $namespace ? $namespace : 'NULL';
  $relationship = $relationship ? $relationship : 'NULL';
  $target_pid = $target_pid ? $target_pid : 'NULL';

  return 'islandora/object/' . $object_pid . '/manage/relationships/delete/' . $namespace . '/' . $relationship . '/' . $target_pid;
}

/**
 * Returns the list of relationships that can be added to this object.
 *
 * @param string $object_pid
 *   the Fedora pid of the object to which the relationship will apply.
 */
function get_possible_relationships($object_pid) {
  $object = islandora_object_load($object_pid);
  if (!$object) {
    return array();
  }
  $options = array();
  if (in_array('islandora:sp_basic_image', $object->models) or in_array('islandora:sp_large_image_cmodel', $object->models)) {
    $options['P138_represents'] = t('represents (is an image or video of)');
  }
  return $options;
  return array(
    'P107_has_current_or_former_member' => t('has current or former member'),
    'P107i_is_current_or_former_member_of' => t('is current or former member of'),
  );
}


/**
 * Returns the list of relationships that can be added to this object.
 *
 * @param string $object_pid
 *   the Fedora pid of the object to which the relationship will apply.
 */
function get_possible_reverse_relationships($object_pid) {
  $object = islandora_object_load($object_pid);
  if (!$object) {
    return array();
  }
  $options = array();
  if (in_array('islandora:sp_basic_image', $object->models) or in_array('islandora:sp_large_image_cmodel', $object->models)) {
    $options['P138i_has_representation'] = t('has representation (is depicted in)');
  }
  return $options;
}

/**
 * Implements hook_islandora_view_object().
 */
function islandora_relationship_editor_islandora_view_object($object, $page_number, $page_size) {
  return NULL;
  $output = theme('islandora_relationship_editor_related_objects', array('islandora_object' => $object));
  return array('Related objects' => $output);
}
