<?php

/**
 * @file
 *
 */

// Namespace for adding relationships 
define('MYNS_URI', 'http://www.cec.org/ontologies/relationships#');
define('FEDORA',"info:fedora/fedora-system:def/relations-external#");

/** 
 * Implements hook_menu().
 */
function islandora_relationship_editor_menu() {
  $items['islandora/object/%/manage/relationships'] = array(
    'title' => 'Relationships',
    'description' => 'Add, remove, or validate related objects',
    'file' => 'Main.inc',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_relationship_editor_display_relationships', 2),
    'access arguments' => array(FEDORA_METADATA_EDIT),
    'type' => MENU_LOCAL_TASK,
  );
  $items['islandora/object/%/manage/relationships/add'] = array(
    'title' => t('Add relationships'),
    'description' => t('Add a new related object'),
    'file' => 'Add.inc',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_relationship_editor_add_relationships', 2),
    'access arguments' => array(FEDORA_METADATA_EDIT),
    'type' => MENU_LOCAL_ACTION,
  );
  $items['islandora/object/%/manage/relationships/delete/%/%/%'] = array(
    'title' => t('Delete relationship'),
    'description' => t('Delete a relationship'),
    'file' => 'Delete.inc',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_relationship_editor_delete_relationships', 2, 6, 7, 8),
    'access arguments' => array(FEDORA_METADATA_EDIT),
    'type' => MENU_CALLBACK,
  );
  $items['admin/islandora_relationships/collections_autocomplete'] = array(
      'page callback' => 'collections_autocomplete',
      'access arguments' => array(FEDORA_METADATA_EDIT),

      'type' => MENU_CALLBACK,
  );

  return $items;
}


/** 
 * Implements hook_theme().
 */
function islandora_relationship_editor_theme() {
  return array(
    'relationship_editor_table' => array(
      'variables' => array('relationships' => NULL),
      'template' => 'relationship-editor-table',
      'path' => drupal_get_path('module', 'islandora_relationship_editor') . '/theme',
    ),
    'islandora_relationship_editor_related_objects' => array(
      'variables' => array('islandora_object' => NULL),
      'template' => 'theme/related-objects',
      'file' => 'theme/related_objects.theme.inc',
    ),
  );
}

/** 
 * Gets delete menu path for a relationship
 */
function islandora_relationship_editor_get_delete_path($objectPid, $namespace, $relationship, $targetPid) {
  $namespace = $namespace ? $namespace : 'NULL';
  $relationship = $relationship ? $relationship : 'NULL';
  $targetPid = $targetPid ? $targetPid : 'NULL';

  return 'islandora/object/' . $objectPid . '/manage/relationships/delete/' . $namespace . '/' . $relationship . '/' . $targetPid;
}

/** 
 * Returns the list of relationships that can be added to this object.
 *
 * @param string $object_pid
 *    the Fedora pid of the object to which the relationship will apply
 */
function get_possible_relationships($object_pid){
  return array(
    FEDORA . '|isMemberOfCollection' => t('is member of collection'),
    MYNS_URI . '|isDraftOf' => t('is draft of'),
    MYNS_URI . '|hasDraft' => t('has draft'),
    MYNS_URI . '|isSummaryOf' => t('is summary of'),
    MYNS_URI . '|hasSummary' => t('has summary'),
    MYNS_URI . '|isUpdateOf' => t('is updated edition of'),
    MYNS_URI . '|hasUpdate' => t('has updated edition'),
    MYNS_URI . '|isResponseTo' => t('is response to'),
    MYNS_URI . '|hasResponse' => t('has response'),
    MYNS_URI . '|isDerivationOf' => t('is derivation of (i.e. is based on)'),
    MYNS_URI . '|hasDerivation' => t('has derivation (i.e. is basis for)'),
  );
}


/** 
 * Implements hook_islandora_view_object().
 *
 * DEPRECATED BECAUSE IT WAS PROOF-OF-CONCEPT
 */
/*
function islandora_relationship_editor_islandora_view_object($object, $page_number, $page_size) {
  $output = theme('islandora_relationship_editor_related_objects', array('islandora_object' => $object));
  return array('Related objects' => $output);
}
 */
